### ISSUE TITLE
Support all Currencies

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#1]
### What is the problem you are trying to solve with this feature?

Some currencies are not listed or supported, this should be resolved.

Originally reported in hay-kot/homebox#918 by @garygan89

### What is the solution you are proposing?

Add all known current currencies to the project

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
A list of all existing currencies can be found on https://en.wikipedia.org/wiki/ISO_4217

Ideally we should find a JSON source of ISO 4217 data that we can use to automatically keep the JSON file up to date with the correct information. While it doesn't really change often, it still seems like something that should be automated.

**Comment by sierikov** [comment]
It would be good to have the ability to turn off or schedule automations within the service. This would enhance the service's autonomy and reduce its reliance on real world. By the way I found a nice [dataset](https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/currency-codes/records?limit=20) with active currency codes from Open Data Soft, and it also has [documentation](https://public.opendatasoft.com/explore/dataset/currency-codes/api/).

**Comment by tankerkiller125** [comment]
It would be my thought that the automation would be more in terms of a Github action or something that keeps the currencies.json file updated, so updating the actual application would still be required to get the new currencies, with no dependencies on outside sources for people self-hosting.

**Comment by katosdev** [comment]
### Immediate term solution:
https://homebox.sysadminsmedia.com/tips-tricks.html#custom-currencies 

Homebox allows you to add custom currencies through an environment variable which could be used to add currencies as required.

**Comment by grbray** [comment]
There seems to be (based on Wikipedia) a maintained list of all active currencies here.

https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml

I know it's in xml format, but it appears to be an ISO supplier?

**Comment by nickrout** [comment]
> ### Immediate term solution:
> https://homebox.sysadminsmedia.com/tips-tricks.html#custom-currencies
> 
> Homebox allows you to add custom currencies through an environment variable which could be used to add currencies as required.

That is a 404 unfortubnately.

**Comment by katosdev** [comment]
> > ### Immediate term solution:
> > https://homebox.sysadminsmedia.com/tips-tricks.html#custom-currencies
> > Homebox allows you to add custom currencies through an environment variable which could be used to add currencies as required.
> 
> That is a 404 unfortubnately.

This is due to recent changes to the docs - link is now:

https://homebox.sysadminsmedia.com/en/tips-tricks.html#custom-currencies

**Comment by katosdev** [comment]
Going to close this one for now as currencies supported through environment variables.
If you'd like a specific currency adding to core, please let me know! 🙂

**Comment by nickrout** [comment]
Sorry to add to a closed issue, but it might help to know what the syntax for the environment variable should be.

**Comment by tankerkiller125** [comment]
@nickrout https://homebox.sysadminsmedia.com/en/tips-tricks.html#custom-currencies

**Comment by nickrout** [comment]
👍
