### ISSUE TITLE
Healthcheck is failing in v0.12.0

### ISSUE THREAD

**Issue by zodac** [sysadminsmedia/homebox#103]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.12.0

### What is the issue you are experiencing?

I updated to the new release, which included https://github.com/sysadminsmedia/homebox/pull/78, but the healthcheck is failing for me:

```
{
  "Status": "unhealthy",
  "FailingStreak": 142,
  "Log": [
    {
      "Start": "2024-07-08T00:02:06.418395991Z",
      "End": "2024-07-08T00:02:06.435254306Z",
      "ExitCode": 8,
      "Output": "http://localhost:7745/api/v1/status:\nRemote file does not exist -- broken link!!!\n"
    },
    {
      "Start": "2024-07-08T00:02:36.435460718Z",
      "End": "2024-07-08T00:02:36.452766069Z",
      "ExitCode": 8,
      "Output": "http://localhost:7745/api/v1/status:\nRemote file does not exist -- broken link!!!\n"
    },
    {
      "Start": "2024-07-08T00:03:06.453302044Z",
      "End": "2024-07-08T00:03:06.470799663Z",
      "ExitCode": 8,
      "Output": "http://localhost:7745/api/v1/status:\nRemote file does not exist -- broken link!!!\n"
    },
    {
      "Start": "2024-07-08T00:03:36.470030488Z",
      "End": "2024-07-08T00:03:36.485622399Z",
      "ExitCode": 8,
      "Output": "http://localhost:7745/api/v1/status:\nRemote file does not exist -- broken link!!!\n"
    },
    {
      "Start": "2024-07-08T00:04:06.485862485Z",
      "End": "2024-07-08T00:04:06.501741215Z",
      "ExitCode": 8,
      "Output": "http://localhost:7745/api/v1/status:\nRemote file does not exist -- broken link!!!\n"
    }
  ]
}
```

Even I go into the container and run the command, I get the error:
```
/app # /usr/bin/wget --no-verbose --tries=1 --spider http://localhost:7745/api/v1/status
http://localhost:7745/api/v1/status:
Remote file does not exist -- broken link!!!
```

I was previously using a healthcheck defined in my docker-compose file (same as the one now in the Dockerfile itself), but that is also failing on the latest version.

I can still successfully hit the **/api/v1/status** endpoint through Google Chrome, so it looks like just a wget issue? I see there was a change to the wget binary installed in https://github.com/sysadminsmedia/homebox/pull/95, might be causing an issue?

### How can the maintainer reproduce the issue?

Run the container, and then check the status of the container

### Deployment

Docker (Windows)

### Deployment Details

I am using the normal Dockerfile, not rootless.

**Comment by tweek11** [comment]
I was just looking into the same thing for unhealthy status:
http://localhost:7745/api/v1/status: Remote file does not exist -- broken link!!! 

Difference between your and mine is that I'm running it on Ubuntu Server 22.04.4 with docker-compose.yml 

Just encase its requested - here is a copy of my docker compose to help compare

version: "3.4"

services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=2048
    - HBOX_WEB_READ_TIMEOUT=60s
    - HBOX_WEB_WRITE_TIMEOUT=120s
    - HBOX_OPTIONS_ALLOW_REGISTRATION=false
    volumes:
      - ./homebox-data:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local


![Homebox-Health-Status](https://github.com/sysadminsmedia/homebox/assets/91363983/5a2d0240-4944-4e2b-9c5a-419e0c66bf40)
