### ISSUE TITLE
Allow use of UNIX sockets instead of ports

### ISSUE THREAD

**Issue by tushev** [sysadminsmedia/homebox#11]
### What is the problem you are trying to solve with this feature?

As of today, homebox supports only HTTP ports, amd does not support unix sockets.

### What is the solution you are proposing?

Add an env variable `HBOX_SOCKET_PATH`. When present, it overrides `HBOX_WEB_PORT` and HTTP server starts listening on the unix socket from specified path.

### Additional context

https://github.com/hay-kot/homebox/issues/510

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
Thanks for the suggestion, I did a quick search and reviewed some other golang code that has implemented this feature and it looks kind of straight forward, but until we start digging into the actual project code itself we won't know for sure.

I won't make any promises in regards to implementing this, but it seems reasonable enough in terms of the self-contained binary version. (I don't know how this would work with docker if at all).

**Comment by tushev** [comment]
Thanks! Yes, it's quite straightforward.

With Docker, it usually works via bind mounts. You then specify socket path in nginx or whatever RP you're using. 
I can write the corresponding docs/examples if necessary, if this feature gets implemented :)

**Comment by katosdev** [comment]
Thanks for the suggestion @tushev - sounds like a good idea to me. Let us dig into the code a little more and wrap our head around a couple of things but sounds reasonably straightforward

**Comment by balki** [comment]
@tankerkiller125 @katosdev I built a go library that helps to support different types of listeners like unix sockets/ systemd sockets.

https://pkg.go.dev/go.balki.me/anyhttp#section-readme

Would you accept a PR for this feature?

**Comment by tankerkiller125** [comment]
@balki if someone submits a PR for it we're all for it.

**Comment by tushev** [comment]
@balki that would be great!
