### ISSUE TITLE
Feature Request: Ability to Move all Child Items when the Location of the Parent Item is Changed

### ISSUE THREAD

**Issue by a2brew** [sysadminsmedia/homebox#110]
### What is the problem you are trying to solve with this feature?

Currently, the location of a child item is not tied to the parent item. For example, if the location on a parent item is changed, the user must manually go into each child item & update the location manually to match. This can create a situation where, if the user doesn't double-check all the child items, the locations could vary and effect accurate location value roll-up.

### What is the solution you are proposing?

A toggle tooltip/switch which a user can select at the parent item level, linking the location of the parent item to all child items beneath it. To maintain flexibility with other user set-ups/use cases, I think it's advisable to keep this as an 'opt in' feature, for users who may want to keep the 'location' of parent/child items decoupled.

### What alternatives have you considered?

N/A, although I'm sure if I had a better understanding of the API, there could be a work around to this.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Bulk actions from #139 should be merged with this issue

**Comment by kav2k** [comment]
Hi @slid1amo2n3e4 - I promise to look into it early next week, but I am very busy this weekend.

**Comment by kav2k** [comment]
I would say I have verified this to my satisfaction.

@slid1amo2n3e4 I am open to directly using PayPal, but there's a question of securely communicating your email for that to me.
If you're not comfortable sharing your email here, I'd suggest a secret Gist (to link it to your account), but how would you prefer to send it to me?

**Comment by kav2k** [comment]
Sent. Please confirm here and I will then withdraw the boss.dev bounty.
