### ISSUE TITLE
Feature Request: Missing Info / Last Updated Search & "Organized" Checkbox

### ISSUE THREAD

**Issue by a2brew** [sysadminsmedia/homebox#113]
### What is the problem you are trying to solve with this feature?

Perhaps I'm unique, but in my typical Homebox workflow, I typically prioritize getting the initial item entry into the app first, and then adding/adjusting information as time allows later on. Today, there does not appear to be a way to view a list of items, based on the date they were last updated or based on what information they might be missing. 

Having the ability to view items in this way would help with keeping item information up to date for insurance purposes, and also identify important gaps in documentation that could impact insurance reimbursement.

### What is the solution you are proposing?

Add/Expose the 'last updated' datapoint for each item & enable that to be a sortable/searchable field. Also allow for the user to search for 'is null'/zero value for certain fields.

Additionally, once all applicable information has been entered, I think it would be useful to have a simple checkbox indicating the item has been fully 'organized', and therefore does not require any further update. That could also be a filter applied to the search, to only display items that do not have the 'organized' box checked.

### What alternatives have you considered?

N/A, although I'm sure this would be possible via a separate workaround, once external database support is integrated. But as I've mentioned in a couple of my other feature requests, I think this would be very valuable as a native feature in the app itself.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Custom sorting would be nice, throwing this open to the community
