### ISSUE TITLE
When my server crashes homebox turns into a brick

### ISSUE THREAD

**Issue by jeranon** [sysadminsmedia/homebox#120]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.12.1 ~ Build: ab3479173735a6946580baee817948513c5f307c

### What is the issue you are experiencing?

If the container running homebox does not stop gracefully (server crash, power failure, etc...) I cannot access the account that I created before the crash. 
I currently have registration turned off, so to get back and running I have to stop the container, turn on registration, start the container, and create a brand new user (using identical credentials, even).
Previous data, as far as I know, is unrecoverable, even though the installation runs flawlessly. It only seems to be user data affected.
So far I haven't done more than testing, so I haven't lost anything of value, but this is a pretty significant detractor from using as a real world solution.

### How can the maintainer reproduce the issue?

- have the container running
- create an account
- crash your system (pull the power, etc... Don't let it gracefully close/turn off) 
- try to login when the system turns on again

### Deployment

Unraid

### Deployment Details

I'm using a socket container on unraid

**Comment by katosdev** [comment]
That seems really strange, and sounds like it's not writing to the database at all...
Are you able to confirm the entry is in the database please?

**Comment by tankerkiller125** [comment]
Unfortunately sqlite is not very good at handling data corruption level events like sudden shutdown in the middle of reads/writes. However it's generally fairly easy to recover with the command line tools as per https://www.sqlite.org/recovery.html we do use WAL mode though, and I'm not entirely sure how recovery works with that.

**Comment by jeranon** [comment]
> That seems really strange, and sounds like it's not writing to the database at all... Are you able to confirm the entry is in the database please?

Absolutely... I'm pretty fresh, though. What do I need to look at/do to get this information?

**Comment by katosdev** [comment]
@jeranon in order to assist with our triage across multiple places, are you able to raise this on our support channel in Discord here please? : 

https://discord.com/channels/1254144480391598163/1254159177358643260

**Comment by katosdev** [comment]
Closing with a view to migrate to Discord.
