### ISSUE TITLE
Feature request: URL in export inventory (CSV)

### ISSUE THREAD

**Issue by melsenm** [sysadminsmedia/homebox#126]
### What is the problem you are trying to solve with this feature?

Is possible to add a column with the url to the item/asset? 
That could by useful to generate barcode for templates with a custom layout and sizing in the Brother P-touch editor software.

### What is the solution you are proposing?

Create a column with url to the item/asset.

### What alternatives have you considered?

You can't create a different design in the QR generator.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [x] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Should be somewhat rather easy to sort.

Triaging as `good first issue`
