### ISSUE TITLE
Feature Request: Add Retail Price and Savings Calculation to Purchase Details

### ISSUE THREAD

**Issue by cschrch** [sysadminsmedia/homebox#128]
### What is the problem you are trying to solve with this feature?

Currently, there is only one field for purchase price in the inventory service. This does not adequately distinguish between the actual value of an item and the price paid, especially when items are purchased at a reduced price. This causes inaccuracies in both expenditure tracking and valuation. Also you can't easily see how much money you've saved.

### What is the solution you are proposing?

Add additional fields to the existing Purchase Details card:

    Retail Price: The original price of the item at the time of purchase.
    Savings: Automatically calculated as the difference between the Retail Price and Purchase Price.

This enhancement will allow for clear and accurate data entry and reporting, reflecting both the true value (Retail Price) of assets and the cost savings. (Retail Price - Purchase Price)

### What alternatives have you considered?

- Always manually adding custom fields for cost and savings.
- Creating a separate "Pricing Details" or "Value Details" card for these new fields.

### Additional context

This feature is related to [sysadminsmedia/homebox#39](https://github.com/sysadminsmedia/homebox/issues/39). Addressing this as part of a broader update could improve the overall functionality and usability of the inventory service.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Hi @cschrch !

Many thanks for submitting your feature request and for the continued support of Homebox.

Unfortunately, at this time we have determined your feature request to be **out of scope** of the project, and would advise that the RRP for the item be tracked elsewhere.

This project is geared more towards actual purchase value and inventory records for home insurance, audit and management capabilities and does not extend the scope to savings tracking.

Apologies for the inconvenience, however we absolutely welcome any other suggestions and requests that you might have.

Thanks,
The Homebox Dev Team.
