### ISSUE TITLE
Search by Asset ID

### ISSUE THREAD

**Issue by blessedbiped** [sysadminsmedia/homebox#135]
### What is the problem you are trying to solve with this feature?

Search does not work for the Asset ID field, which would help for someone wanting to put an item away which cannot support a sticker (most hand tools would lose a sticker, but I can write or engrave a number on them to search)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
You can do this already 

![IMG_0525](https://github.com/user-attachments/assets/c02b00d9-ceb8-452b-915f-08df565f50d6)

**Comment by katosdev** [comment]
Thanks @hay-kot !
Will close this as a non-issue for now, but @blessedbiped please re-open if you’re having issues 😄
