### ISSUE TITLE
Search does not look at custom fields

### ISSUE THREAD

**Issue by salsaw** [sysadminsmedia/homebox#144]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.12.1

### What is the issue you are experiencing?

The global search feature does not search the values of custom fields created for an item. The search feature should be able to look at all properties for an item when perform a search.

### How can the maintainer reproduce the issue?

1. Create a custom field in any item
2. Search for the value contained for that custom field
3. 0 results will return

### Deployment

Docker (Synology)

**Comment by 101br03k** [comment]
Do you use thee actual custom fields option in the search feature?
![image](https://github.com/user-attachments/assets/d7ac54bd-99be-453b-97b4-097abcf829c9)
enabeling the above in the search feature will result in the following and works good for me: 
![image](https://github.com/user-attachments/assets/665952c7-1d05-4c14-97d0-590e347859b1)

**Comment by katosdev** [comment]
@salsaw please can you advise if this is still an issue or if this is working with the details from @101br03k

**Comment by salsaw** [comment]
I guess this could be an issue or enhancement request, depending on how the expected search is supposed to work. Using the `Custom Field` selector doesn't actually search for a value in that field. I can choose the custom field and the dropdown will display the values of the custom fields, but that's an option value at this point and not really a search for a free text field. 

Take this example. I have a custom field called `Barcode` and I can select one just fine
![image](https://github.com/user-attachments/assets/65e2ed00-fcf4-49ab-a11b-dd43d61b25f2)

My expectations is that the global search can look into all fields, not just the description, for search results
![image](https://github.com/user-attachments/assets/87b257d9-e56f-4503-8840-508880033aa7)

FWIW here is a link to a similar issue I created in the archived project https://github.com/hay-kot/homebox/issues/869. I can bring this one over as a separate issue if it is not related.

**Comment by salsaw** [comment]
In my case, I'll use the `Serial Number` field for my use case. That will be a workaround for needing a custom field. The `Serial Number` field does get searched.

**Comment by JingleheimerSE** [comment]
I'd argue that this issue should be reopened even though Salsaw found a work around for his use case. I'm trying to do something similar and found it very odd that the search function did not return any results for a match on a custom field.

**Comment by katosdev** [comment]
> I'd argue that this issue should be reopened even though Salsaw found a work around for his use case. I'm trying to do something similar and found it very odd that the search function did not return any results for a match on a custom field.

This issue was merged into the parent epic, #438
