### ISSUE TITLE
Currencies missing from "Shared Group settings":

### ISSUE THREAD

**Issue by SuperOlle** [sysadminsmedia/homebox#145]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.12.1

### What is the issue you are experiencing?

Currencies are missing from the list in shared group settings:

![image](https://github.com/user-attachments/assets/020abe0d-fc45-4d3f-b0ef-708d3caebbfd)

I'm looking for SEK but can't find it but it exists in:

backend/internal/core/currencies/currencies.json

(I'm no dev or anything like that so maybe I'm looking at the wrong file, I've done my best... :( ) 

### How can the maintainer reproduce the issue?

I've tried to deploy it on two different hosts with the same result so I think this is present on all deployments.

### Deployment

Docker (Linux)

**Comment by 101br03k** [comment]
Can confirm that for example SEK is not in the list.

**Comment by tankerkiller125** [comment]
The newly automated Currencies file has not yet made it into a tagged release build of Homebox. The last release did not have SEK (or a lot of other currencies that are now listed in that file). This will be fixed upon the next release.

If you wanted to validate that it shows up before the next actual release, you could do so by using the `:nightly` tagged docker image (which is build directly from master).

**Comment by katosdev** [comment]
As @tankerkiller125 has stated the new currencies list isn’t yet deployed, we are now using an action to try to keep this up-to-date and synced though so hopefully we can minimise missing currencies going forwards!

apologies for any issues

**Comment by SuperOlle** [comment]
> The newly automated Currencies file has not yet made it into a tagged release build of Homebox. The last release did not have SEK (or a lot of other currencies that are now listed in that file). This will be fixed upon the next release.
> 
> If you wanted to validate that it shows up before the next actual release, you could do so by using the `:nightly` tagged docker image (which is build directly from master).

Sorry for my late reply when you guys replied so quickly, running the nightly now and it's working perfectly! 

Time to report another bug :D

**Comment by katosdev** [comment]
Marking as closed as currencies are available in new version following the workflow sync.
