### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by saschabrockel** [sysadminsmedia/homebox#146]
### What is the problem you are trying to solve with this feature?

I'm running HomeBox in Docker and I use the latest tag of the image but I don't know which one is the latest and if the correct one was pulled and do not have a simple way to check it without comparing hashes or diving deep.

### What is the solution you are proposing?

Just add the correct version in the Dockerfile because currently, it is just: `LABEL Name=homebox Version=0.0.1`

Or an even better version in my opinion, just add simple v12.1 below the Sign-Out button in a lighter color. And maybe as other tools do all other information you also need to debug things if someone reports a bug. Of course, you can also do this on a separate page but I think the little label would be way less work to do.

Great tool though thanks for keeping it alive!

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by 101br03k** [comment]
If you go to profile and scroll down it should say it there. 
But I agree that it could be located better.

**Comment by saschabrockel** [comment]
Ah okay sorry then! Or if it would be documented at least :) but I guess many people would not expect it there
