### ISSUE TITLE
Edit notifier does not show old value

### ISSUE THREAD

**Issue by saschabrockel** [sysadminsmedia/homebox#147]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.12.1

### What is the issue you are experiencing?

I would expect the notifier to show the current value and maybe fix a typo e.g. But the input field is empty.

### How can the maintainer reproduce the issue?

Create a notifier and type something in and then just press edit.

### Deployment

Docker (Linux), Unraid

**Comment by 101br03k** [comment]
Is it correct that for you in this windows it does not show the cost value?
(as you can see it says update in the button so this is indeed the edit funtion of the maintenance schedule)
![image](https://github.com/user-attachments/assets/3e623816-a84e-490e-9317-5bf0eea21968)

**Comment by saschabrockel** [comment]
No, I mean here:
![image](https://github.com/user-attachments/assets/cc1d64ef-531c-43eb-b98f-214925d4c780)

**Comment by 101br03k** [comment]
I can confirm that that is not a local issue, same for me (Version: v0.12.1 ~ Build: ab3479173735a6946580baee817948513c5f307c)
