### ISSUE TITLE
Export Inventory does not include data from the Notes field

### ISSUE THREAD

**Issue by alternativesurfer** [sysadminsmedia/homebox#151]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.13.0

### What is the issue you are experiencing?

When I Export Inventory, the "HB.notes" field does not populate with any of the data in that field for the entries.

Example entry:
![image](https://github.com/user-attachments/assets/27faca8e-5c93-46e1-b0bb-9a68dc346c17)

Exported file entry:
![image](https://github.com/user-attachments/assets/a510ce36-09d2-410d-bf74-817a41abaf2b)

### How can the maintainer reproduce the issue?

Create an entry, add data to the Notes field, export to CSV.

### Deployment

Docker (Linux)

### Deployment Details

default docker compose.

**Comment by 101br03k** [comment]
I can duplicate this (docker Version: v0.13.0 ~ Build: e05135207008c1a930166d517e82b971c9e199e3)
