### ISSUE TITLE
The ability to search through labels

### ISSUE THREAD

**Issue by danielrosehill** [sysadminsmedia/homebox#156]
### What is the problem you are trying to solve with this feature?

When you create lots of labels (hundreds, thousands) it's no longer practical to scroll through the list when you wish to assign one or multiple labels to an item

### What is the solution you are proposing?

Search functionality for the UI element. 
You can search to quickly find the label(s) you need.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by dopeCape** [comment]
i can take this one

**Comment by dopeCape** [comment]
my bad did not see that the frontend is written in Vue, I just assumed it was react. genuinely sorry
