### ISSUE TITLE
Support HEIC images

### ISSUE THREAD

**Issue by adripo** [sysadminsmedia/homebox#165]
### What is the problem you are trying to solve with this feature?

Using HEIC images format

### What is the solution you are proposing?

Support HEIC format

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
What part of the application doesn't support HEIC? What isn't working? etc.

This request right now is so vague I wouldn't know where to start to even consider fixing it. Further details are required.

**Comment by 101br03k** [comment]
What I have found using the images from https://filesamples.com/formats/heic
![image](https://github.com/user-attachments/assets/47089975-0725-4c49-9254-cac687afd826)
![image](https://github.com/user-attachments/assets/cf77a324-fab1-4be9-b707-b5def687f2ea)

**Comment by tankerkiller125** [comment]
Doing some quick research this isn't something we are really in control of unless we convert the files. Digging into the code we simply spit out whatever was given to us into the HTML img tags.

Browser support is limited: https://caniuse.com/heif

**Comment by 101br03k** [comment]
@adripo I don't know if youre in a postiton to check if it works wit safari, but it is currently browser limited unless you convert the images (which can be done very easy using a selfhosted instance of [convertX](https://github.com/C4illin/ConvertX) )
Unless you have any ideeas I think the issue can be closed but I will leave that up to the issue creator or repo maintainer.

**Comment by adripo** [comment]
Apologies for the delayed response. The issue I wanted to highlight is the same one mentioned by @101br03k, where item photos and covers are not visible if the images are in HEIF format. I haven't been able to test this on Safari, but it seems likely that browser limitations are causing the problem.

While I could convert the images before uploading, it's not feasible when capturing pictures directly from the browser during item creation in Homebox. The ideal solution, in my view, would be for Homebox to automatically convert all photos to a widely compatible format like WebP during the upload process. Is this something you can implement and add to the backlog?

**Comment by mcarbonne** [comment]
Maybe an alternative is to only accept widely supported image formats on the input form:
```diff
diff --git a/frontend/components/Item/CreateModal.vue b/frontend/components/Item/CreateModal.vue
index 24e4f7a..ff40a7a 100644
--- a/frontend/components/Item/CreateModal.vue
+++ b/frontend/components/Item/CreateModal.vue
@@ -11,7 +11,7 @@
         <div class="flex justify-center">
           <div>
             <label for="photo" class="btn">{{ $t("components.item.create_modal.photo_button") }}</label>
-            <input id="photo" type="file" accept="image/*" style="visibility: hidden" @change="previewImage" />
+            <input id="photo" type="file" accept="image/png,image/jpeg,image/gif" style="visibility: hidden" @change="previewImage" />
           </div>
           <BaseButton class="rounded-r-none" :loading="loading" type="submit">
             <template #icon>
```

I don't have any apple devices so I can't test it, but according to [this](https://masteringlaravel.io/daily/2023-10-27-how-to-get-rid-of-heic-files-in-your-app), it is supposed to work.
