### ISSUE TITLE
Duckdns Homebox not reachable when ipv6 filled

### ISSUE THREAD

**Issue by Saturo78** [sysadminsmedia/homebox#167]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.13.0

### What is the issue you are experiencing?

I access homebox via duckdns and a fritzbox.
I notice that homebox is always unreachable after an ip change. 
After some trial and error, I found out that access works again if I delete the ipv6 address in duckdns.
Unfortunately, the fritzbox fills it again with the next update.

### How can the maintainer reproduce the issue?

access homebox via duckdns and fritzbox.
set update script in fritzbox or provide ip adresses manual to duckdns

### Deployment

Docker (Linux)

### Deployment Details

Raspberry pi 4b with portainer
Fritzbox 7530AX

**Comment by ecshreve** [comment]
I've had some issues with ddns and ipv6 in the past (different hardware and provider, but similar behavior). Did a little digging around and found [this article that might be helpful](https://decatec.de/home-server/dyndns-home-server-mit-einer-fritzbox-mit-ipv4-und-ipv6-dual-stack-betreiben/)

> ...the FritzBox is spoiling our plans: If you access the DynDNS domain using IPv6 (most browsers do this automatically if both IPv4 and IPv6 are offered), you end up at the FritzBox web interface. But that's exactly what we don't want; the FritzBox should actually forward the request to the machine behind it.
>
> This seems to be a limitation of the FritzBox: IPv6 traffic is apparently always terminated at the FritzBox and not forwarded to the actual destination.

**Comment by tankerkiller125** [comment]
Given I'm unable to replicate this issue in the many various ways I've thought of to try to replicate this without an actual FritzBox, and the fact that it appears that this is some sort of FritzBox limitation/issue, I think it would be best to close this issue at the moment. With the only real suggestion/solution being to disable IPv6 support in some fashion (as much as that pains me to say as someone who loves IPv6 and deploys it everywhere).
