### ISSUE TITLE
Indeterminate 'Invalid email or password' error

### ISSUE THREAD

**Issue by lareeth** [sysadminsmedia/homebox#174]
### First Check

* [x]  This is not a feature request
* [x]  I added a very descriptive title to this issue.
* [x]  I used the GitHub search to find a similar issue and didn't find it.
* [x]  I searched the documentation, with the integrated search.
* [x]  I already read the docs and didn't find an answer.

### Homebox Version

v0.13.0

### What is the issue you are experiencing?

After an indeterminate amount of time, the API calls to homebox API fail, leaving the frontend with empty content, when deleting the session cookies, and trying to log back in, I get given the error `Invalid email or password` both from the frontend and from the `/api/v1/users/login` API.

The frontend when failing makes many calls to `/api/v1/users/self` which returns `{"error":"Unknown Error"}`

This issue has only started since upgrading from v0.12.1 to v0.13.0, which I did around a week ago, since then I get this issue multiple times a day every day. Once I restart the homebox container, I am able to login successfully again.

These are the error logs from when this happens

```
11:49AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="interrupted (9)" req_id=homebox/hYZ2sQH0Vb-009398
11:49AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="interrupted (9)" req_id=homebox/hYZ2sQH0Vb-009399
11:49AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="interrupted (9)" req_id=homebox/hYZ2sQH0Vb-009400
11:49AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="authorization header or query is required" req_id=homebox/hYZ2sQH0Vb-009401
11:49AM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_auth.go:119 > failed to authenticate error="invalid username or password"
```

### How can the maintainer reproduce the issue?

1. Login to homebox v0.13.0
2. Wait
3. API calls start to fail
4. Delete session cookies
5. Try to login and get error
6. Restart homebox container
7. Login now works again

### Deployment

Docker (Linux)

**Comment by tankerkiller125** [comment]
We're looking into the issue, but so far I haven't managed to replicate it. Just something to ask here, are you by chance hosting the persistent storage (Sqlite Database) on a network storage location like NFS, FreeNAS, etc.? Or is it just a standard hard drive/SSD?

**Comment by lareeth** [comment]
I'm using Sqlite with host mapping to a local directory, the system is running on an SSD. There is no network storage.

**Comment by katosdev** [comment]
Sorry @lareeth - I meant to check back in on this one. Following the recent releases, is this one still an issue for you? 🙂

**Comment by tankerkiller125** [comment]
We have not heard back since our latest releases if this is still an issue or not.

If you are still having an issue, please re-open this issue.

**Comment by lareeth** [comment]
I will upgrade to the latest release and raise a new issue if I'm still experiencing issues.
