### ISSUE TITLE
Changeable default page size of list items

### ISSUE THREAD

**Issue by EmPiFree** [sysadminsmedia/homebox#183]
### What is the problem you are trying to solve with this feature?

When I have more than 10 items in a location, and I don't recognize that I habe the "next page" button, I am missing some items. When the default count of displayed items would be changeable, it would help me a lot!

### What is the solution you are proposing?

Add a dropdown box to select between different amount of displayed items on the same page (like 10, 25, 50, 100)
Not sure if we should make the table bigger or keep the table size, but use a scroll function, to scroll through all items.

### Additional context

![image](https://github.com/user-attachments/assets/110eda67-f48a-42bb-a01f-2c5715b237b1)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
This should be fairly straight forward I believe based on my knowledge of the API and functions that call it. The UI implementation part will probably be the hardest part honestly. Will have to dig into it.

**Comment by EmPiFree** [comment]
Just saw the PR @tonyaellie 
Great work, thanks!
