### ISSUE TITLE
Corner radius inconsistent

### ISSUE THREAD

**Issue by petruut** [sysadminsmedia/homebox#188]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.4

### What is the issue you are experiencing?

![image](https://github.com/user-attachments/assets/39fe83ee-4516-4af4-96cf-c1cca86df371)

### How can the maintainer reproduce the issue?

MacOS, Safari, latest version. Homepage

### Deployment

Docker (Linux)

**Comment by tankerkiller125** [comment]
I thought we had sorted out that text problem, apparently not though, will have to dig deeper into that one, as for the corner radius I'll dig into that as well.
