### ISSUE TITLE
Recurrent maintenance schedule

### ISSUE THREAD

**Issue by petruut** [sysadminsmedia/homebox#189]
### What is the problem you are trying to solve with this feature?

Plenty of items will require scheduled maintenance (e.g. quarterly changes/ checks) - would be super to have recurrence for maintenance tasks when adding them in.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by 101br03k** [comment]
Is this the same as #172 ?

**Comment by petruut** [comment]
You're right - it is close to it. I suppose 172 has a slightly more complicated user experiences in mind (whereas this is literally just adding recurrence to maintenance - no logic around last or next etc.)

**Comment by katosdev** [comment]
I will close this one off with a view to managing under #172 for now 😄
