### ISSUE TITLE
Make it obvious an item is archived

### ISSUE THREAD

**Issue by AstroPhotoJay** [sysadminsmedia/homebox#198]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

14

### What is the issue you are experiencing?

Nowhere on the item listing page or item detail page does it show if an item is archived. The only way to tell if an item is archived on the item detail page is by entering edit mode. On the search screen, there is nothing to show if an item is archived so you have to first search without the "show archived items" toggle, then search a second time with the "show archived items" toggle on and then look for anything new.

Ideally, a red "archived" bubble would be added to the item on the search screen, similar to the location bubble. 
![image](https://github.com/user-attachments/assets/d0d1f07b-77b6-48d9-b2a2-b149366aa199)

On the item detail page, there would be plenty of ways to show an item is archived, but one idea would be to change the background colour of the homebox icon next to the item name.
![image](https://github.com/user-attachments/assets/120e5671-4a55-4f25-8819-562b9e1aeebe)

### How can the maintainer reproduce the issue?

Use item search screen
Scan QR code for archived item
View any archived item

### Deployment

Docker (Linux)

**Comment by tonyaellie** [comment]
![image](https://github.com/user-attachments/assets/ccbf1c14-8a6a-4834-80d8-362c93f1b2e2)
maybe something like this to match how we currently show that an items insured
