### ISSUE TITLE
Update namespaces to sysadminsmedia

### ISSUE THREAD

**Issue by katosdev** [sysadminsmedia/homebox#20]
### What is the problem you are trying to solve with this feature?

Files are currently referencing the archived hay-kot repository, and need amending to the new sysadminsmedia namespace.

### What is the solution you are proposing?

Review and update **all** golang files to the new namespace. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
Used some quick regex and replaced the namespace across all of the files, and pushed up the change and confirmed successful docker build.

**Comment by katosdev** [comment]
> Used some quick regex and replaced the namespace across all of the files, and pushed up the change and confirmed successful docker build.

Super! Great work @tankerkiller125 
Thanks for handling
