### ISSUE TITLE
Copy Button does not work

### ISSUE THREAD

**Issue by saschabrockel** [sysadminsmedia/homebox#211]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.14.1 ~ Build: 25c76522d6687c2545dddbcd51e3e4af95393d3f

### What is the issue you are experiencing?

I press the copy button for Model Number on an item and the animation works but nothing is copied. It also does not seem to work for the other fields. By the way, it would be nice if it were possible for all values, not only these two.

### How can the maintainer reproduce the issue?

1. Create an item and save it
2. Enter the view (not edit) view of the item
3. Click the copy button next to the model number
4. Paste it somewhere and you see it was not copied

### Deployment

Docker (Linux), Unraid

**Comment by katosdev** [comment]
I am not able to replicate this on our [Demo](https://demo.homebox.software/) - Can you please try it here @saschabrockel ?

**Comment by tankerkiller125** [comment]
For good measure I also just tested across a few devices in our demo, and I was also unable to replicate, can you give us some more details about the browser, OS, etc. that might help us debug this down? I for example lack Apple Devices to test on, so I've only tested on various Windows and Linux browsers.

**Comment by saschabrockel** [comment]
Hmm I try it again later. I'm using Windows 11 and the latest version of Google Chrome.

**Comment by katosdev** [comment]
> Hmm I try it again later. I'm using Windows 11 and the latest version of Google Chrome.

Ran Chrome as my test on my win11 box, as well as on my work laptop - Unable to replicate on either i'm afraid.

**Comment by saschabrockel** [comment]
It works on my notebook too. I have the feeling something is terribly wrong with my PC. I'm sorry to have wasted your time. Thank you for checking anyway!

**Comment by katosdev** [comment]
> It works on my notebook too. I have the feeling something is terribly wrong with my PC. I'm sorry to have wasted your time. Thank you for checking anyway!

No time wasted at all! 
Hope you get your PC sorted, maybe turn on clipboard history and see what (if anything) is rocking up in there? Could be something as simple as you need to allow the website permissions to access clipboard.
