### ISSUE TITLE
Footer text containing version number does not apply theme styles

### ISSUE THREAD

**Issue by zebrapurring** [sysadminsmedia/homebox#223]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.14.1 ~ Build: 25c76522d6687c2545dddbcd51e3e4af95393d3f

### What is the issue you are experiencing?

When changing the theme, the version number in the footer of the site does not change the style.

For example, using the Dracula theme the footer is almost not visible:

![homebox_footer](https://github.com/user-attachments/assets/12509429-c93a-4eee-a0f5-74c91a0b0ade)

### How can the maintainer reproduce the issue?

Select a dark theme.

### Deployment

Other

**Comment by tankerkiller125** [comment]
It actually is applying correctly; the issue is that some themes just have a bad contrast for the CSS coloring that the footer text uses VS the background color.

**Comment by zebrapurring** [comment]
I see, didn't know that the themes are pre-defined. Then I will close the issue, thanks!
