### ISSUE TITLE
Limit how long Purchased From and Sold To can be

### ISSUE THREAD

**Issue by tonyaellie** [sysadminsmedia/homebox#232]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I can replicate the issue inside the Demo install.

### Homebox Version

v0.14.1

### What is the issue you are experiencing?

![image](https://github.com/user-attachments/assets/db3e81de-b9e3-4b1a-bca1-6e178792cb86)

There is no limit to how long purchased from and sold to can be.

Should prob have a limit of 255 or 1k like most other fields

### How can the maintainer reproduce the issue?

1. Create an item.
2. Go to the edit page and put in text.
3. Watch in amazement as it will let you save text of seemingly any length (at least up to 1mil chars).

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by 101br03k** [comment]
To be fair, I see this as a feature not a bug, unless you did find any problems with Homebox after inserting and saving 1mil chars?

**Comment by tonyaellie** [comment]
Mainly just made the page very laggy and didn't wrap so the page was very wide.

**Comment by tankerkiller125** [comment]
We could make the text wrap, however, large text does have issues both with being rendered (after all it is a frontend JS Framework), and on top of that, if we ever do any form of search/indexing on those fields it would slow down search significantly.
