### ISSUE TITLE
Figure out binary version build

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#24]
We need to sort out how to build the actual binary versions of the project, now that docker is taken care of binaries would be the next logical move.

**Comment by cksidharthan** [comment]
this would be a good option i think https://goreleaser.com/

**Comment by tankerkiller125** [comment]
I believe the project already uses goreleaser? Or at least there's a branch with, I'll have to dig into it more.

While I've worked with Go in the past it's generally been on projects with extremely detailed documentation for building, or premade build scripts. It seems that this project never got that documentation written, nor scripts created.

Hopefully, once I get this sorted out manually though I'll be able to translate it into a Github action that can upload the binaries to the Github release automatically for us to save some time on each release.

**Comment by hay-kot** [comment]
I used goreleaser to build and publish the release.

Basically, you create/push a tag and then it kicks of this workflow https://github.com/sysadminsmedia/homebox/blob/main/.github/workflows/tag.yaml

**Comment by tankerkiller125** [comment]
@hay-kot Thanks for the insight! I thought I saw goreleaser someplace I just couldn't remember where exactly.

**Comment by katosdev** [comment]
> I used goreleaser to build and publish the release.
> 
> Basically, you create/push a tag and then it kicks of this workflow https://github.com/sysadminsmedia/homebox/blob/main/.github/workflows/tag.yaml

Fantastic, thanks for the insight @hay-kot

**Comment by tankerkiller125** [comment]
A manual build was completed successfully (and added to the release), digging into how best integrate the goreleaser tooling with the new docker image production. In theory I should be able to just run both at the same time with no issues I think.
