### ISSUE TITLE
Maximum character limit in descriptions

### ISSUE THREAD

**Issue by jsspen** [sysadminsmedia/homebox#244]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I can replicate the issue inside the Demo install.

### Homebox Version

0.14.2 ~ Build: 214b16a26ecfc05c922da310414d4e0c2b16e03c

### What is the issue you are experiencing?

It seems there's a hard limit on description length for items. When attempting to create an item or save an existing item with a description length that exceeds 1,000 characters there is a "Failed to (Save/Create) Item" popup. Browser console just shows a 500 error.

### How can the maintainer reproduce the issue?

Use this 1,001 character dummy text in a description field: _Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio sagittis convallis urna pharetra elementum mi eu malesuada rhoncus cum aliquam lectus montes. Dignissim primis nullam ligula senectus penatibus mollis ante fringilla curae ultrices massa sollicitudin convallis. Blandit purus vivamus faucibus luctus dui semper penatibus nulla ullamcorper nascetur himenaeos phasellus accumsan. Sociosqu aptent amet curae aliquam ultrices facilisi dui fermentum elementum molestie ullamcorper cubilia lorem. Congue condimentum habitasse nunc egestas vulputate scelerisque pretium eu magnis natoque praesent integer molestie. Sagittis dictumst convallis eleifend praesent venenatis luctus egestas at sollicitudin sit mattis morbi consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Odio sagittis convallis urna pharetra elementum mi eu malesuada rhoncus cum aliquam lectus montes. Odio sagittis convallis urna pharetra elementum mi eu malesuada rhoncus cum aliquam lectus montes. Odio sagits._

### Deployment

Other

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

Executable in a Proxmox LXC

**Comment by tonyaellie** [comment]
Is this not a duplicate of https://github.com/sysadminsmedia/homebox/issues/150 ?

**Comment by jsspen** [comment]
> Is this not a duplicate of #150 ?

You're right. Apologies, I'm not sure how I missed that in my searches.
