### ISSUE TITLE
Blank Login Screen When Behind Cloudflare Zero Trust

### ISSUE THREAD

**Issue by jtitley** [sysadminsmedia/homebox#249]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [   ] I can replicate the issue inside the Demo install.

### Homebox Version

Latest

### What is the issue you are experiencing?

It appears that when Cloud Flare (and I suspect any reverse proxy) must authenticate the issue occurs. Without knowing the architecture I'd say the issue is that the login screen is cached on the client, and the first request is a Web socket call of some sort, or a request for a JavaScript file. In this case, the reverse proxy will intercept with login HTML or I guess block a websocket call. 

Just a guess, maybe someone smarter than me can understand it. 

I'm going to see if overriding the browser cache TTL in cloudflare solves the issue. This would force a pull of the home page from the origin triggering a login intercept. 

It's also possible the OIDC PR will solve the issue as I assume there will be some sort of callback that will be intercepted. 

### How can the maintainer reproduce the issue?

Install cloudflared container in docker on the same virtual network as homebox
Setup a tunnel from homebox:7745 to homebox.mydomain.com
Setup a new Application for homebox.mydomain.com

Login
Wait a day ☺ or thump session in zero trust forcing reauthentication. 
Access homebox.mydomain.com

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

I don't think this is relevant to the issue.

**Comment by katosdev** [comment]
Myself and @tankerkiller125 both run our instances behind Cloudlare, as indeed are Demo and Nightly - So unfortunately it sounds like a configuration issue on your part.
Can you provide further details on your Cloudflare configuration? 🙂

**Comment by katosdev** [comment]
Any update on this one please @jtitley

**Comment by katosdev** [comment]
Closing due to no answer and inability to replicate. Will reopen if more details provided.
