### ISSUE TITLE
Add support for setting a focal point on images

### ISSUE THREAD

**Issue by mwayne** [sysadminsmedia/homebox#252]
### What is the problem you are trying to solve with this feature?

When primary images are displayed in card view, their aspect ratio is maintained by clipping the image to fit within the image container. In some situations, the shown portion of the image is not ideal:

<img width="379" alt="Screenshot of an item card with its primary photo cut off" src="https://github.com/user-attachments/assets/f97eee79-f02f-4c87-9fa1-3636a413e84b">

### What is the solution you are proposing?

To add new X and Y focal point fields to attachments that can be set by simply clicking the desired point within an image:

WIP:

<img width="536" alt="New X and Y focal point fields in the Attachment Edit modal" src="https://github.com/user-attachments/assets/43337aa0-a9b1-4bf1-9521-293897d9cb48">

And here's the focal point selector, represented by a red dot:

<img width="513" alt="A red dot placed over a photo, representing its focal point" src="https://github.com/user-attachments/assets/d19cd7a1-0818-40ef-a2ce-7c548ff232d5">

When coordinates are set, the `object-position` CSS property can be used to center the view on the chosen focal point.

For the backend implementation, adding `focal_point_x` and `focal_point_y` columns to the `attachments` table seems like the most straightforward solution, but this doesn't really make sense for attachments that aren't photos. Then again, neither does the `primary` column I suppose? I'm brand new to the codebase, so alternative implementations are welcome.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by Openuser87** [comment]
Has been marked as not planned, although this is quite important for usability; many pictures in item list get really non-informative after they are handled automatically. E.g., have a look at this:

![Image](https://github.com/user-attachments/assets/a2371b9e-98b0-4cc8-a3e8-6805fde87955)

Could we at least have an option to use the whole image as thumbnail?
