### ISSUE TITLE
Cannot update/add Purchase Price to an item

### ISSUE THREAD

**Issue by grizly1326** [sysadminsmedia/homebox#263]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.15.0

### What is the issue you are experiencing?

When trying to update the purchase price as an example I cannot save it `Failed to save item` if I use the Developer mode in chrome i can see the error:

```
{"error":"Unknown Error"}
```

If i ran the instance locally and im checking the log i can see this error in there:
```bash
ERROR occurred error="body decoding error: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into float64" req_id=
```

This also happens for new entries not just updating

---

When checking what type of that property it is i can see in case of the OK communication the type is string.
![Image](https://github.com/user-attachments/assets/28756e8b-6007-40e6-8c5d-11b81d07acbf)

---

When checking the type in the **NOT** OK communication the type is int:
![Image](https://github.com/user-attachments/assets/3b478786-339a-47db-98e4-b3c7b9a8b959)

---

When i try to modify the POST message manually to `66` it was changed in the DemoBox.

I think maybe the place where it should be updated is here (but not that sure as haven't checked the full project to understand what type it should be): [purchasePrice](https://github.com/sysadminsmedia/homebox/blob/a70bb227a9fa3063a1f7c59eaaf6fa6defb68a60/frontend/lib/api/types/data-contracts.ts#L184)

### How can the maintainer reproduce the issue?

Can be seen on the DemoBox: <https://demo.homebox.software/item/e40419e7-b5e3-42cb-893d-fe1de9206a08/edit> (just have to toggle the advanced view).

### Deployment

Docker (Linux), Docker (Windows), Docker (Synology), Unraid, Other

### OS Architechture

x86_64 (AMD, Intel), ARM64, ARM/v7

**Comment by sgiraz** [comment]
I'm experiencing this issue too! Additionally, I recall that in previous versions, it was possible to enter a decimal number for the purchase price. This seems more logical, considering many electronic items are priced at less than 1 dollar/euro.

**Comment by tankerkiller125** [comment]
This is a known issue at the moment, a fix has been found and committed, we're doing some final validation and testing before publishing a patch version.

**Comment by tankerkiller125** [comment]
It's going to take a little while longer for the docker images to build, however v0.15.1 has been tagged and released to resolve this issue.

**Comment by tankerkiller125** [comment]
Discovered that this issue is only partially fixed in the latest patch release, working to resolve this fully and properly.

**Comment by tankerkiller125** [comment]
OK, now this is properly fixed and deeply tested.
