### ISSUE TITLE
Label Generator showing incorrect asset ID

### ISSUE THREAD

**Issue by nikkojonasevie** [sysadminsmedia/homebox#289]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.15.2

### What is the issue you are experiencing?

I had about 10 assets enters and everything seem to be fine. When I go to the label generator it appears some of my later assets are either not shown in the label generator or have the complete wrong asset id. What might I be doing wrong?

I was able to reproduce on the demo instance. Asset 000-009 and Asset 000-008 are showing incorrect on the label generator page

### How can the maintainer reproduce the issue?

Create new item and go to label generator to see asset doesn't have correct asset id

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
Can you share a screenshot of this from the Demo instance? I'm having some issues with replicating this because I don't quite understand what's not being displayed correctly. I have however found some significant issues with labels getting malformed by long item names (which I have committed a "fix" for that should be in nightly tomorrow)

**Comment by w1ntermute0** [comment]
I'm trying out homebox for the first time today so apologies if I'm doing something dumb but I noticed something similar.  I created a few items and then imported about 20 items from CSV.  When I generate the QR codes the asset ID (and the URL in the QR code) doesn't match the item name.  It looks like maybe the asset names are sorted alphabetically and the asset IDs are sorted numerically and then these two lists are put together in that order to make the QR codes.

![Image](https://github.com/user-attachments/assets/3d8ab911-77f2-4c23-827b-72f67244945f)

![Image](https://github.com/user-attachments/assets/6e27ed89-1b49-42f1-9d3e-180aa5f71628)

**Comment by nikkojonasevie** [comment]
@tankerkiller125 the screen shot and issue @w1ntermute0 commented is exactly what I'm seeing as well. For some reason I can't access the demo instance anymore. Is it possibly down?

**Comment by tankerkiller125** [comment]
Thanks! This makes it much more clear, I'll be honest I didn't even think to check the asset ID number compared to names.

I'll take a look (or if @katosdev beats me to it he will), and we'll see if we can find and sort the problem.

**Comment by w1ntermute0** [comment]
I've been trying to figure out git, VScode, async functions, and vue with limited success.  I was able to make the labels generate correctly but this is probably at best inelegant and likely a dumb way to do it.  Anyway in case it helps anyone, here are the sections of label-generator.vue that I changed, happy to share the whole file somehow if it's easier:



```
function getItem(n: number, myitem: { id: string; name: string; location: { name: string } } | null): LabelData {

    return {
      url: getQRCodeUrl(goodAssetIDs[n]),
      assetID: goodAssetIDs[n],
      name: myitem?.name ?? "_______________",
      location: myitem?.location?.name ?? "_______________",
    };
  }
```


below that I defined  goodAssetIDs and filled it:


```
var goodAssetIDs: string[]=[];
  const { data: allFields } = await useAsyncData(async () => {
    const { data, error } = await api.items.getAll();

    if (error) {
      return [];
    }

    for (let i = displayProperties.assetRange; i < displayProperties.assetRangeMax; i++) {
        const myTemp = ( await api.items.get( data.items[i].id  )).data.assetId;
        goodAssetIDs[i]= myTemp;
        console.log("Found: " + myTemp);
      };

      return data;
  });

```

**Comment by katosdev** [comment]
> I've been trying to figure out git, VScode, async functions, and vue with limited success. I was able to make the labels generate correctly but this is probably at best inelegant and likely a dumb way to do it. Anyway in case it helps anyone, here are the sections of label-generator.vue that I changed, happy to share the whole file somehow if it's easier:
> 
> ```
> function getItem(n: number, myitem: { id: string; name: string; location: { name: string } } | null): LabelData {
> 
>     return {
>       url: getQRCodeUrl(goodAssetIDs[n]),
>       assetID: goodAssetIDs[n],
>       name: myitem?.name ?? "_______________",
>       location: myitem?.location?.name ?? "_______________",
>     };
>   }
> ```
> 
> below that I defined goodAssetIDs and filled it:
> 
> ```
> var goodAssetIDs: string[]=[];
>   const { data: allFields } = await useAsyncData(async () => {
>     const { data, error } = await api.items.getAll();
> 
>     if (error) {
>       return [];
>     }
> 
>     for (let i = displayProperties.assetRange; i < displayProperties.assetRangeMax; i++) {
>         const myTemp = ( await api.items.get( data.items[i].id  )).data.assetId;
>         goodAssetIDs[i]= myTemp;
>         console.log("Found: " + myTemp);
>       };
> 
>       return data;
>   });
> ```

Thanks! I’ll review this and sort something for tomorrow
