### ISSUE TITLE
Long item titles fail to wrap effectively on small display windows

### ISSUE THREAD

**Issue by ag14spirit** [sysadminsmedia/homebox#290]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.15.2

### What is the issue you are experiencing?

Long Location and Item title paths overrun the screen area due to a failure of the interface design to accommodate text lengths that fit within the character limits of the user input fields. The text wrapping issue appears on an iPhone 13 Pro on multiple iOS versions.

### How can the maintainer reproduce the issue?

See attached images for example of arbitrarily long item title and location path.

![Image](https://github.com/user-attachments/assets/c15d389b-a249-4efe-9a4f-5e873a52e66a)
![Image](https://github.com/user-attachments/assets/ac4538b7-5f15-4cc5-b8c1-0061e0d98d52)
![Image](https://github.com/user-attachments/assets/40d9ec99-5747-4217-b8c5-7465fecbee5b)

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by ag14spirit** [comment]
That was _fast_! I had every intention of offering a pull request when I got back to my computer.

Thanks!

**Comment by tankerkiller125** [comment]
It was the first thing I saw when I opened my IDE and Github issues, and it was simple enough to knock out before I started working on much more complex issues (Multi-DB type support)
