### ISSUE TITLE
Fix TSVs actually being CSVs

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#3]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.3

### What is the issue you are experiencing?

Originally reported in hay-kot/homebox#910 by @betapictoris the exported files are comma seperated, but have the TSV extension.

### How can the maintainer reproduce the issue?

1. Export BOM
2. Examine the file in a text editor

### Deployment

Docker (Linux)

**Comment by betapictoris** [comment]
Thanks for working on this!

**Comment by icanc0** [comment]
This issue remains unfixed, there's another export function that calls on `/api/v1/items/export`. I'm going to fix it along with #5. 

@tankerkiller125 @katosdev is there a reason why we had both TSV and CSV for different types of exports? 

![image](https://github.com/sysadminsmedia/homebox/assets/44480394/ba7b83c5-d665-4b41-ab17-fe8ddc79d9ea)
> image above shows a call to `/api/v1/items/export`

![image](https://github.com/sysadminsmedia/homebox/assets/44480394/e838f11e-ff48-48df-a14f-63d6ed8de6a1)
> image above shows both export methods

Seems like the file formats are still reversed, here's the result from the current main branch: 
![image](https://github.com/sysadminsmedia/homebox/assets/44480394/afccde38-7a3e-4db1-b5c4-187d3d62c478)

**Comment by katosdev** [comment]
> @tankerkiller125 @katosdev is there a reason why we had both TSV and CSV for different types of exports?

Honestly, no idea why both are there. Makes sense to switch to just CSV I believe 👍🏻

**Comment by icanc0** [comment]
> Honestly, no idea why both are there. Makes sense to switch to just CSV I believe 👍🏻

Alright, gonna do a quick PR so i get used to the process again.
