### ISSUE TITLE
Hide unused portions of the app in the main drawer

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [sysadminsmedia/homebox#308]
### What is the problem you are trying to solve with this feature?

Removing "bloat" that I do not use from the main screen. I'm sure there's more than just me out there wondering if this is possible.

### What is the solution you are proposing?

When viewing yourinstance.tld/maintenance, have a toggle to "hide from home screen."

Just having it hide the list item and button from `drawer-side shadow-lg` would be sufficient!

### What alternatives have you considered?

I could just ignore the list item, or run a browser script to hide it.

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [x] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
After some review, we've decided not to take on attempting this, in general the extra menu options are very minimal, and you wouldn't exactly gain any extra space or anything like that by removing unused ones.
