### ISSUE TITLE
Hope to support Simplified Chinese

### ISSUE THREAD

**Issue by Q-1515** [sysadminsmedia/homebox#32]
### What is the problem you are trying to solve with this feature?

This application is very helpful to me, but it is not convenient for other users to read

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
I haven't gotten too deep into the code, so I haven't dug into any `i18n` related stuff yet (if it even exists, haven't gotten that far or needed it). In general though I'm a strong supporter of internationalization support in software.

**Comment by icanc0** [comment]
i18n on the frontend should be easy, assuming that your family speaks a single language. we wont need API changes to support items with names in multiple languages etc.

**Comment by katosdev** [comment]
Labelling as good first issue, open to community help! 👍🏻

**Comment by tankerkiller125** [comment]
For anyone wanting to implement this feature. I don't mind any implementation. But I would really prefer an ICU Message format compatible/standard implementation given its flexibility and inclusiveness (given it was designed by unicee).

**Comment by tankerkiller125** [comment]
Sill working on the full feature implementation, and getting all the existing strings switched over, however those wanting to contribute languages can start doing so at https://translate.sysadminsmedia.com/projects/homebox/frontend/

**Comment by tankerkiller125** [comment]
I'm going to close this issue as it's i18n itself has been implemented. It's up to the community at this point to implement the languages they want to see via the weblate link shared previously.
