### ISSUE TITLE
Use established solution to show relative time in languages

### ISSUE THREAD

**Issue by adamkleizer** [sysadminsmedia/homebox#321]
### What is the problem you are trying to solve with this feature?

While trying to translate to Hungarian, I'm at a roadblock. While it is easy to write "X ago" and "in X" in English with X being easily changed between "1 year" and "5 seconds", X has different suffixes (cases) in Hungarian for the past and future: "1 év**vel** ezelőtt"-"1 év múlva", "5 másodperc**cel** ezelőtt"-"5 másodperc múlva".

Luckily this is a solved issue, the included date-fns has an intlFormatDistance method to show the distance between dates with a specific locale: https://date-fns.org/v4.1.0/docs/intlFormatDistance

### What is the solution you are proposing?

Display relative dates with date-fns call to intlFormatDistance. Remove "in X", "X ago" and related time period translations.

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [x] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by adamkleizer** [comment]
Found the source in question: https://github.com/sysadminsmedia/homebox/blob/main/frontend/composables/use-formatters.ts

I can now say I'll look into it if no one else picks this up.

**Comment by tankerkiller125** [comment]
@adamkleizer feel free to pick this up, I'd be happy to assign this issue to you as well if you'd like.

**Comment by adamkleizer** [comment]
You can assign it to me, I'll try to fix it in the near future.
