### ISSUE TITLE
The location is missing in `Parent Location` if it is written in non-latin only characters

### ISSUE THREAD

**Issue by Maks1mS** [sysadminsmedia/homebox#324]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.15.2 ~ Build: c6158e7c9ebf8ce4c921078b71f71fe2e16606c4

### What is the issue you are experiencing?

I can't create items and child locations in locations that use only non-Latin characters (for example `ПРОВЕРКА` or `支票`). It will works as expected only if i have latin character or symbol (`_ПРОВЕРКА` or `zПРОВЕРКА`)

### How can the maintainer reproduce the issue?

1. Create location with name `ПРОВЕРКА` or `支票`
2. Try to select `Parent Location` in item or location

### Deployment

Other

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tonyaellie** [comment]
Can you recreate this issue with https://vnext.homebox.software/home?

**Comment by Maks1mS** [comment]
> Can you recreate this issue with https://vnext.homebox.software/home?

It looks like it works great.
