### ISSUE TITLE
[Feature Request] Option to disable further signups

### ISSUE THREAD

**Issue by al-lac** [sysadminsmedia/homebox#326]
### What is the problem you are trying to solve with this feature?

If i want to make my HomeBox site public, it would be good to have the option to disable further signups without an invite code. Otherwise anyone could just create an account on my HomeBox instance.

### What is the solution you are proposing?

Add a switch somewhere that disables further signups. As far as i know there is no admin panel as of yet, this would also fit in there pretty well.

### What alternatives have you considered?

Only make the site reachable via VPN. But that makes it way harder to share it with others.

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by 101br03k** [comment]
see https://homebox.software/en/configure-homebox.html#env-variables-configuration and then the var 

HBOX_OPTIONS_ALLOW_REGISTRATION

**Comment by al-lac** [comment]
Thanks @101br03k, did not see this option.

**Comment by grotesque** [comment]
> ./homebox --mode production --options-allow-registration 0 &

Above command doesn't seem to work. What am I doing wrong?

**Comment by tonyaellie** [comment]
> > ./homebox --mode production --options-allow-registration 0 &
> 
> Above command doesn't seem to work. What am I doing wrong?

I believe you need to use `false` not `0`
