### ISSUE TITLE
Application Localization Does Not Reflect the System Locale

### ISSUE THREAD

**Issue by evgeniysharapov** [sysadminsmedia/homebox#329]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.15.2 Build c6158e7c9ebf8ce4c921078b71f71fe2e16606c4

### What is the issue you are experiencing?

I have a fresh LXC container in Debian 12 with following `env`

```
SHELL=/bin/bash
PWD=/opt
LOGNAME=root
XDG_SESSION_TYPE=tty
container=lxc
MOTD_SHOWN=pam
HOME=/root
LANG=en_US.UTF-8
XDG_SESSION_CLASS=user
TERM=linux
USER=root
SHLVL=2
XDG_SESSION_ID=4694
XDG_RUNTIME_DIR=/run/user/0
HUSHLOGIN=FALSE
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAIL=/var/mail/root
_=/bin/env
OLDPWD=/root
```

When I start `homebox` and go to `http://<ip>:7745` it shows in Russian translation (see screenshot)

![Image](https://github.com/user-attachments/assets/89eca77d-6dc0-42ac-8df2-c90a606c1e25)

When it comes to replicating it in Demo - I see demo install in Russian also. 

 

### How can the maintainer reproduce the issue?

1. Download release 0.15.2
2. unpack it into `/opt` 
3. Start a binary `/opt/homebox`

### Deployment

Other

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

Linux, straight up starting the binary in a Debian 12 LXC container.

**Comment by 101br03k** [comment]
fyi, altough since you closed it and proberly found out, Homebox takes the browser locale.

**Comment by tankerkiller125** [comment]
@101br03k is correct, the translations have an order they use to determine which language to display which goes as following: 

`setting from user profile save in browser storage -> browser locale -> english`

**Comment by evgeniysharapov** [comment]
Yeah, that was the case. When I accessed the homebox from anonymous browser
session it showed up in English.
