### ISSUE TITLE
"Quick Statistics" text not visible with default Theme Settings

### ISSUE THREAD

**Issue by woodleyb** [sysadminsmedia/homebox#34]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [ ] I used the GitHub search to find a similar issue and didn't find it.
- [ ] I searched the documentation, with the integrated search.
- [ ] I already read the docs and didn't find an answer.

### Homebox Version

v0.11.0

### What is the issue you are experiencing?

Within the Home screen page, under the Quick Statistics header, the headers for "Total Value" / "Total Items" / "Total Locations" / "Total Labels" isnt visible with the dark background of the header boxes. This occurs with the default Theme, as well as selecting a few others that had dark colours.
This was also present on the Demo version of Homebox (https://homebox.fly.dev/)
Issue:
![Capture_homebox1](https://github.com/sysadminsmedia/homebox/assets/47429831/69181d9a-72d7-4587-87ff-dc502b119647)
Highlighting text:
![Capture_homebox2](https://github.com/sysadminsmedia/homebox/assets/47429831/9d05e512-c639-4e9a-adef-34333f0fff5f)

### How can the maintainer reproduce the issue?

- Access Home page of Homebox (https://homebox.fly.dev/ > login using demo login)
- Issue will be present on the Home tab. 

### Deployment

Docker (Linux)

**Comment by tankerkiller125** [comment]
Do you have any plugins in your browser that force dark modes on websites or anything like that? Attempting to replicate the issue in Chrome, Edge, and Firefox on my end did not have the same issue.

![image](https://github.com/sysadminsmedia/homebox/assets/3457368/c7b72e2e-b7da-417e-8d3a-c5ad301a33d8)

**Comment by ELind77** [comment]
I'm having the same issue.  Including on Android where I don't think browser plugins should have an effect. Switching to the Aqua theme was a fine workaround but it's definitely a bad first introduction to the app.

**Comment by tankerkiller125** [comment]
Testing a bunch more I was finally able to replicate this on a tablet. But still not on any of my desktops. So this one will be fun to try and debug and fix.

But it is confirmed now.

**Comment by ELind77** [comment]
If we have it working and not working on two environments where we have a console/inspector in the browser we should be able to see which CSS rule is controlling the color. But I'm not sure how to trace that back into the source.

**Comment by tankerkiller125** [comment]
Replicated the issue on a work laptop, and started digging through the CSS related to it, and it appears to have an extremely complex logic behind it. But basically `:after` and `:before` are being set 3 separate times (or at least listed 3 times in the CSS browser dev tools). I'll dig into the CSS a bit more once I'm home for the weekend.

**Comment by fiala-sns** [comment]
I am still seeing this on v0.13.0 in docker.
If desktop is set to dark mode (with Firefox theme on automatic) is expected that the text won't be visible? Or am I doing something wrong?
