### ISSUE TITLE
Show Parent Locations of an item in search results

### ISSUE THREAD

**Issue by mingw128** [sysadminsmedia/homebox#344]
### What is the problem you are trying to solve with this feature?

Searching for an item will show you the child location that it's in, but not the parent locations that the location itself is in.

For instance, if "cleaning supplies" are located on Shelf 3 in File Cabinet 3 in the Garage, the search results will show "Shelf 3"

### What is the solution you are proposing?

Show all of the parent locations in the search results, so in this case it would show Garage > File Cabinet 3 > Shelf 3.

### What alternatives have you considered?

The alternative is to click into the item from the search results to see its location tree listed at the top, which works fine, but this enhancement request is to improve functionality by providing the info within search results and therefore require less clicking.

### Additional context

current state:
![Image](https://github.com/user-attachments/assets/4d9f6985-cf04-4ac2-97dc-edbd9c6e0793)

future state (something like this):
![Image](https://github.com/user-attachments/assets/da8329a3-da11-4a0d-b2ab-54208248d9aa)

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [x] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by mingw128** [comment]
this is awesome, works perfect, thank you!

**Comment by zebrapurring** [comment]
Thanks for the improvement! Could we also update the badge location in the home screen on mobile browsers?
