### ISSUE TITLE
Add Ukrainian language

### ISSUE THREAD

**Issue by OriginalSimon** [sysadminsmedia/homebox#348]
### What is the problem you are trying to solve with this feature?

Need to add support for the Ukrainian language in the project. The translation for all texts has already been completed (100%).

### Additional context

https://translate.sysadminsmedia.com/projects/homebox/frontend/uk/

### Contributions

- [x] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [x] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tankerkiller125** [comment]
This will be done automatically by weblate. It runs the commit phase every so often.
