### ISSUE TITLE
Allow webp photos to be attached at create time

### ISSUE THREAD

**Issue by joestump** [sysadminsmedia/homebox#350]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

latest

### What is the issue you are experiencing?

When you select "Photo" (see screenshot) on Create > Item/Asset, you can't select `webp` photos. However, you *can* add them via the Edit tab and they render fine in the UI. 

![Image](https://github.com/user-attachments/assets/fa3ac016-14a5-46d3-a76e-03c0de19ee15)

### How can the maintainer reproduce the issue?

1. Go to Create > Item/Asset
2. Click "Photo"
3. Try and select a `webp` photo

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

This is via Firefox on macOS.

**Comment by tankerkiller125** [comment]
This issue was already addressed in https://github.com/sysadminsmedia/homebox/pull/284, it just hasn't made it to a release just yet (but soonish).
