### ISSUE TITLE
Support ROOT_URL for deploy

### ISSUE THREAD

**Issue by amasslaw** [sysadminsmedia/homebox#356]
for some reason，that I only had one domain name 【xxx.fun.com】。
so could Homebox can support for deploy at a sub path? such as 【xxx.fun.com/homebox】

**Comment by ivangrimaldi** [comment]
hello @amasslaw, if still interested, added a comment here https://github.com/sysadminsmedia/homebox/discussions/322#discussioncomment-13236252 
I did that with NGINX reverse proxy
