### ISSUE TITLE
Homebox SVG logo missing in Safari due to size not specified

### ISSUE THREAD

**Issue by lmaced0** [sysadminsmedia/homebox#360]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.16

### What is the issue you are experiencing?

Missing width="250" height="250" in the svg portion of the code here: frontend/components/App/Logo.vue

![Image](https://github.com/user-attachments/assets/482b716b-eecb-424f-8da8-1d61c212b8fd)

Fixed when added size:

![Image](https://github.com/user-attachments/assets/1122efad-a2a1-4d6b-9368-30710a53739e)

### How can the maintainer reproduce the issue?

Open Homebox on Safari (iOS or macOS).

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
Of course it's Safari, it's always Safari when it comes to things like this.

**Comment by katosdev** [comment]
Apologies for the delays @lmaced0 ! This should be fixed under #400 if you'd like to give that a go? 👍🏻

**Comment by katosdev** [comment]
Reopening as issue still apparent. Further investigation required.
