### ISSUE TITLE
Attaching a HEIC image file for receipt or attachment renames file and removes extension

### ISSUE THREAD

**Issue by backyardaussie** [sysadminsmedia/homebox#369]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.16.0

### What is the issue you are experiencing?

Attaching to an item a photo of a receipt captured by iPhone which creates a HEIC file format, HomeBox renames the file to a random GUID naming format and removed the file extension.

When trying to view the attached file for the item either by download or by view/open fails to work. The downloaded file when manually has the extension added to the file downloaded - works and can be opened

Would rather the file name not be altered and the file extension not be removed?

### How can the maintainer reproduce the issue?

Attach a HEIC file to an item for receipt or attachment and then save, try to open it or download it

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by 101br03k** [comment]
> I used the GitHub search to find a similar issue and didn't find it.

I knew it existed, and found it by searching for heic in the closed issue's: #165

What browser are you using?

> As of August 2024, only Safari supports HEIC format natively. 

[source]https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format#Web_browsers)

**Comment by backyardaussie** [comment]
Safari.. that's is what I am using.. hmmm

I did find that closed issue, but I opened this as it was not exactly the same issue.

Homebox is renaming the file and removing the extention too. So that could be causing more problems with the trying to open/view or download

**Comment by tankerkiller125** [comment]
Right now, the file name is altered, and it will remain that way for general use internally. As I work through the storage provider changes it's my intention that when clicking the download button for attachments it will pass through the original name (which will fix the issue for downloads from the actual button).

Due to the issues with HEIC, the file will not get downloaded as HEIC again but will instead be downloaded as whatever iOS converts it to during upload.

**Comment by backyardaussie** [comment]
cool.. can't wait to see how well this project progresses :)
