### ISSUE TITLE
Shared Locations or Per-Location Invites

### ISSUE THREAD

**Issue by mikeperalta1** [sysadminsmedia/homebox#37]
### What is the problem you are trying to solve with this feature?

It would be nice to have finer control over location sharing. I would like to maintain control of my main account's locations but share specific locations with other accounts.

For example, two people living in the same home might each want to manage their own bedrooms to retain control and privacy. But they might both want to manage common areas together.

### What is the solution you are proposing?

Two possible ideas so far:

* Per-Location invite links
* A permissions area for each location, where you can select/check other users to receive read and/or write access to your locations.

### What alternatives have you considered?

I was thinking of making a separate account for the common areas and having it invite each personal account. But that would force you to login/logout of multiple accounts to manage all locations, rather than staying logged in to just one account.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Merging with #109
