### ISSUE TITLE
Log being spammed even though Loglevel is set to info

### ISSUE THREAD

**Issue by chh345** [sysadminsmedia/homebox#377]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

latest

### What is the issue you are experiencing?

Running homebox inside a docker container the logs on the host are spammed by non informative entries.

> 12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021515
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021515 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021516
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021516 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021517
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021517 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021518
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021518 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021519
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021519 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021520
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021520 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021521
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021521 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021522
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021522 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021523
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021523 status=0
12:54PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021524
12:54PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=OPTIONS path=/ rid=homebox/GXnFaYHGwX-021524 status=0

### How can the maintainer reproduce the issue?

docker-compose.yml

> services:
  homebox:
    container_name: homebox
    hostname: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless

    restart: unless-stopped

    environment:
      - TZ=Europe/Berlin
      - HBOX_MODE=production
      - HBOX_OPTIONS_ALLOW_REGISTRATION=true # set to false later
      - HBOX_OPTIONS_AUTO_INCREMENT_ASSET_ID=true
      - HBOX_WEB_MAX_UPLOAD_SIZE=50
      - HBOX_STORAGE_DATA=/data/
      - HBOX_STORAGE_SQLITE_URL=/data/homebox.db?_fk=1
      - HBOX_MAILER_HOST=
      - HBOX_MAILER_PORT=587
      - HBOX_MAILER_USERNAME=
      - HBOX_MAILER_PASSWORD=
      - HBOX_MAILER_FROM=
      - HBOX_SWAGGER_HOST= # default 7745
      - HBOX_SWAGGER_SCHEMA=https # alt https
      - HBOX_LOG_LEVEL=info # debug # info
      - HBOX_LOG_FORMAT=text # alt json
      - HBOX_WEB_MAX_UPLOAD_SIZE=10

    volumes:
      - /mnt/media/Docker/homebox/data:/data/

    networks:
      media-net:
        ipv4_address: 10.11.11.21
    mac_address: '0A-B1-0B-0D-0E-AB'

    expose:
      - 7745

### Deployment

Docker (Linux)

### OS Architechture

ARM64

**Comment by tankerkiller125** [comment]
This is not a bug, INFO will show all requests to the URLs and requests.

To only show errors and warnings switch to warn, error, or critical.

**Comment by codersaur** [comment]
Even with HBOX_LOG_LEVEL=warn the logs are still spammed by the ../go/src/app/internal/web/mid/logger.go messages
