### ISSUE TITLE
lables not showing in item screen view

### ISSUE THREAD

**Issue by 5zud3n** [sysadminsmedia/homebox#396]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.16.0

### What is the issue you are experiencing?

lables not showing in item screen view
![Image](https://github.com/user-attachments/assets/12d113c3-a56d-4c36-883b-bcd0f16da1e0)

### How can the maintainer reproduce the issue?

go to any Item / Assest and check the lables.
same issue observered in demo portal.

### Deployment

Docker (Linux)

### OS Architechture

ARM64

**Comment by tankerkiller125** [comment]
I've confirmed this one, will have to investigate what's happening here.

**Comment by katosdev** [comment]
Picking this up - Will investigate alongside sorting a fix for #360

**Comment by katosdev** [comment]
Fixed in Nightly.
https://nightly.homebox.software
