### ISSUE TITLE
Roll up subitem's value into parent item/location

### ISSUE THREAD

**Issue by ChrisQGeorge** [sysadminsmedia/homebox#40]
### What is the problem you are trying to solve with this feature?

Currently, the value of all assets are tracked individually, but in the case where a parent item consists of multiple subitems, it is difficult to determine the value of the parent item. Likewise, the value of the items in a location is similarly difficult to determine.

### What is the solution you are proposing?

A field should be added to locations and parent items that is the summed value of all child items. This should not affect the total value as not to be double counted, and the parent item itself should also still be able to be given a value, which is also summed in the summed value field. 

### What alternatives have you considered?

An alternative would be to go to the parent item and sum all values of child items manually with a calculator.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by katosdev** [comment]
Pretty sure I saw some work for this elsewhere so I’ll have a quick review and see what I can find later today
