### ISSUE TITLE
Version Display is not working

### ISSUE THREAD

**Issue by grbray** [sysadminsmedia/homebox#45]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Latest?

### What is the issue you are experiencing?

The version display on both the login page and the Profile page are displaying 
`Version: ~ Build:`

Makes it very difficult to report proper bugs

### How can the maintainer reproduce the issue?

Hit the login page or go to the Profile page.

### Deployment

Docker (Linux)

**Comment by tankerkiller125** [comment]
This is very strange, and hard to track down it seems, locally during development while building I get `Version: nightly ~ Build: HEAD` which for current development is correct. But it seems that when it's actually published something doesn't get set right.

**Comment by grbray** [comment]
I think it was broken on haykots last build too. Just never reported there maybe

**Comment by tankerkiller125** [comment]
For sure something related to the docker build process, just tested the nightly docker build and it has no versions set. So I'll have to dig into what's different there compared to the various binary build methods.
