### ISSUE TITLE
Ability to add image when creating item

### ISSUE THREAD

**Issue by AstroPhotoJay** [sysadminsmedia/homebox#58]
### What is the problem you are trying to solve with this feature?

For use cases that rely on items containing an image or attachment, the lack of image attachment in the item creation modal is a big friction point.

### What is the solution you are proposing?

Include the "attachment" field in the item creation modal.

### What alternatives have you considered?

none

### Additional context

Carrying over discussion from [original repo](https://github.com/hay-kot/homebox/discussions/858).

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by cjmielke** [comment]
Here you go : https://github.com/sysadminsmedia/homebox/pull/173

I've been wanting this feature for more than a year, so I finally just sat down and hacked at it. Works, but probably not ideal. It's best if people more familiar with Vue.js perfect it.

And hello from a fellow astronomer!

**Comment by tankerkiller125** [comment]
#173 Has been merged and completed. Because it was merged with the wrong fix keyword though I'm not sure how the bounty software will handle it, if needed I'll reach out to them to get it sorted.

**Comment by salsaw** [comment]
I just want to point out that the button to add a photo may not show up in an iPhone 12 using Safari. It seems to appear hidden. A workaround is to  zoom out to 75% or less and it will show up. Thanks for implementing this.

**Comment by tankerkiller125** [comment]
@salsaw please check https://nightly.homebox.software several CSS fixes have been implemented to fix this.

**Comment by adiov** [comment]
@tankerkiller125 The latest nightly build looks great!
