### ISSUE TITLE
Parsing of asset IDs as 32-bit integers breaks compatibility with existing databases

### ISSUE THREAD

**Issue by zebrapurring** [sysadminsmedia/homebox#60]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.11.0-02bc58e

### What is the issue you are experiencing?

After 1233606d192fa5f6ffea9bc5d27f68ba336756c0, databases containing asset IDs with 64 bits are no longer compatible. Querying a 64-bit asset ID throws the following error:

```
ERROR occurred error="strconv.ParseInt: parsing \"3004083325098833068\": value out of range"
```

### How can the maintainer reproduce the issue?

Create an item with a random asset ID value larger than 4294967295 and query the API endpoint `GET /v1/assets/{id}`.

### Deployment

Other

**Comment by zebrapurring** [comment]
As a workaround I limited all my asset IDs to use only 31 bits (`[0, 2147483648)`), but this will not always be possible:

```sh
sqlite3 homebox.db "update items set asset_id = asset_id % 2147483648"
```

**Comment by tankerkiller125** [comment]
Thanks for the report, I'll get this patched up. It was corrected to 32 bit because in theory it already was being parsed as 32 bit the entire time.

It appears though that golang might be a bit more fluid about that though compared to other languages I'm more accustomed to like .NET
