### ISSUE TITLE
Publish first docker image under our namespace

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#7]
We need to publish the first image under our namespace just to get it out, it doesn't need any changes or anything, just a working published version.

**Comment by devzwf** [comment]
Hi 
i am maintaner of the Unraid template for Homebox.
I have been made aware of this take over after the original project get archived.
When the container is ready i will update the unraid template.

great to see the project going again.

**Comment by tankerkiller125** [comment]
Awesome! I actually just found out about the Unraid templates on Unraid and hadn't yet looked into updating them when the time came but was going to. Given you found us, that makes it way easier!

**Comment by katosdev** [comment]
Thanks so much @devzwf thats really kind of you! 
we’ll aim to get a container sorted ASAP!

**Comment by tankerkiller125** [comment]
A dev container with the `:master` tag has been published for the amd64 platform. I'm working on getting all the platforms built and working, and then I'll hopefully push a `:latest` tag.

Right now I'm doing this manually on my computer instead of Github actions because I really need to do a re-write of the existing actions to work better towards our general work style.

**Comment by katosdev** [comment]
CC @devzwf RE the above from @tankerkiller125 :)

**Comment by tankerkiller125** [comment]
As a note, :master is intended as a dev tag really, I'm still working on publishing a more solid "production" tag. Which will be at the :latest tag like the previous images from the original project.

**Comment by tankerkiller125** [comment]
The first `:latest` and `:latest-rootless` versions have been tagged, along with the various version tags `:0`, `:0.11`, etc. and it's fully automated.

Additionally `:main` is the long term tag for the immediate development build. And `:nightly` for the scheduled development builds.

As of today, the documentation on our readme, and our documentation pages are correct.

**Comment by devzwf** [comment]
I will update the unraid template and test 
thanks

**Comment by tankerkiller125** [comment]
@devzwf HUGE thanks!

**Comment by katosdev** [comment]
> Template updated and tested.

Thanks so much! Really appreciate that
