### ISSUE TITLE
After logging in, you are not redirected to the url originally requested

### ISSUE THREAD

**Issue by harrisony** [sysadminsmedia/homebox#75]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

latest

### What is the issue you are experiencing?

If you are not logged in, you are not redirected to the page you requested after logging in. 

This gets real annoying when you're in your storage unit and bent yourself in a precious position to scan a QR code only to get sent to the login page. 

### How can the maintainer reproduce the issue?

without being signed in

- visit a url (e.g.) http://homebox.lan/a/123
- login
- where is my item 123?! this is the home page

### Deployment

Docker (Linux)

**Comment by katosdev** [comment]
Fixed in https://github.com/sysadminsmedia/homebox/pull/76 - Closing.
