### ISSUE TITLE
Publish the documentation site to our own domain

### ISSUE THREAD

**Issue by tankerkiller125** [sysadminsmedia/homebox#8]
We need to publish the existing documentation to our own website/subdomain for the project. Ideally at the same time or before the docker container.

**Comment by tankerkiller125** [comment]
Documentation has been published to https://homepage.sysadminsmedia.com

Switched to vitepress as I simply have more experience with it than MKDocs, though it does come with extra benefits, they aren't the primary reasons for the switch.

**Comment by adrianj12** [comment]
> Documentation has been published to https://homepage.sysadminsmedia.com
> 
> Switched to vitepress as I simply have more experience with it than MKDocs, though it does come with extra benefits, they aren't the primary reasons for the switch.

\* [https://homebox.sysadminsmedia.com](https://homebox.sysadminsmedia.com)

**Comment by tankerkiller125** [comment]
@adrianj12 :man_facepalming: how do I screw these things up so often.
